### ISSUE TITLE
eror database

### ISSUE THREAD

**Issue by tjementhel** [sutam21/candycbt#4]
Kesalahan Versi Database
Mohon maaf versi database anda tidak sesuai dengan database versi ini mohon gunakan versi terbaru !!
![errr](https://user-images.githubusercontent.com/61520272/80394700-695b5f80-88dc-11ea-9843-ccb292cc57a7.png)

**Comment by tjementhel** [comment]
Kesalahan Versi Database
Mohon maaf versi database anda tidak sesuai dengan database versi ini mohon gunakan versi terbaru !!
![errr](https://user-images.githubusercontent.com/61520272/80394644-50eb4500-88dc-11ea-808a-02bca1fef39e.png)

**Comment by sutam21** [comment]
> Kesalahan Versi Database
> Mohon maaf versi database anda tidak sesuai dengan database versi ini mohon gunakan versi terbaru !!
> ![errr](https://user-images.githubusercontent.com/61520272/80394700-695b5f80-88dc-11ea-9843-ccb292cc57a7.png)

Cara Memperbaikinya adalah dengan cara install database yang terbaru
